### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by urstruktur** [sarahschuetz/Blockhalde#3]
framerate stays around 8 FPS
and undefineable render problem
![issue](https://cloud.githubusercontent.com/assets/11160574/20760310/f450d472-b71f-11e6-8cae-a4e76902f5ae.jpg)

**Comment by tapirbug** [comment]
Would you mind providing information on how to reproduce the error? Btw there is a big merge with graphics stuff coming any moment

**Comment by tapirbug** [comment]
While you are waiting for your fix, have a look at this beautiful picture:
<img width="884" alt="screen shot 2016-11-30 at 18 55 01" src="https://cloud.githubusercontent.com/assets/6675136/20764464/94f146b0-b72e-11e6-9c07-5880463614f1.png">

**Comment by urstruktur** [comment]
im stunned by the beauty of it!

can't provide you with a lot of information on reproducing it. i run the DesktopLauncher and this is what is see. if i move the camera, i wait for ~1 second and then there is a change, but its not behaving as expected - im always looking kindof upwards. console is logging "Initial generation time: 461"

**Comment by urstruktur** [comment]
tried it another time and noticed a strange thing: if the window of blockhalde is not active/focused but still visible it is working correctly still receiving my mouse position 😨
as soon as i focus the window its behaving crazy again

**Comment by urstruktur** [comment]
found the source of the problem 
if i remove the line 20 in InputSystem it "works":
`Gdx.input.setCursorCatched(true);`

**Comment by tapirbug** [comment]
Thanks, libgdx – good job on finding a temporary fix, though 😘.

Don't know how setCursorCatched works, but maybe we could duplicate the functionality by setting an empty image as the mouse cursor when the game window gets focus? Since I cannot reproduce the bug, would you mind looking into this? [Here](http://gamedev.stackexchange.com/questions/86509/how-can-i-change-the-appearance-of-the-mouse-cursor-in-libgdx) is some info on setting a custom mouse cursor.

~~Mouse behavior may need additional work anyway. When using mouse position deltas to determine camera movements (hi @shaendro , thanks for the commit!), the mouse position should not get stuck on one side of the window. It would have to be reset to the opposite side of the window, still providing accurate deltas for input code. I suggest adding a `MouseSystem` or something similar that manages this related stuff.~~

EDIT: Ok after talking to @shaendro I realize this mouse position wrapping is completely unnecessary. He manages this by resetting the mouse position to the window center on each update. That's a way better solution to the problem anyway 🙃

EDIT2: I just got thinking, @uvitar if you want to include mouse input for the GUI, you should discuss that with @shaendro

**Comment by urstruktur** [comment]
Thanks for thinking about solutions. Let's discuss it in detail on monday.
& @shaendro thanks for fixing the problem, so ill close the issue! 😃

**Comment by jul-ya** [comment]
Another beautiful picture, as I don't know where to put it: This is still basic and buggy, buuuuut - 
![ao_and_artifacts](https://cloud.githubusercontent.com/assets/11027763/20868709/2ab64eb2-ba62-11e6-91c4-37ae6a81471d.PNG)

Ambient Occlusion!
